# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "cloud-task-infra"
    encrypt = true
    key     = "eu-central-1/vpc/terraform.tfstate"
    profile = "ersel-local"
    region  = "eu-central-1"
  }
}
